[tool.poetry]
name = "jesseagent"
version = "0.1.0"
description = "Personal knowledge and task Agent"
authors = ["Jesse"]
readme = "docs/README.md"
packages = [{ include = "jesseagent" }]
include = ["jesseagent/prompts/**/*.txt"]


[tool.pyright]
venvPath = "."
venv = ".venv"


[tool.poetry.scripts]
jesseagent = "jesseagent.cli.main:app"

[tool.poetry.dependencies]
python = "3.12.*"
typer = "*"
rich = "*"
pydantic = "*"
pydantic-settings = "*"
google-genai = "*"
chromadb = "*"
yt-dlp = "*"
youtube-transcript-api = "*"
loguru = "^0.7.3"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"
ruff = "*"
mypy = "*"
poethepoet = "*"
pylint = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
format-check = "ruff format --check ."
format = "ruff format ."
static = "mypy --strict jesseagent"
lint = "ruff check ."
test = "pytest --cov=jesseagent --cov-report=term-missing --cov-fail-under=90"
check = ["format-check", "lint", "static", "test"]

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
files = ["jesseagent"]
